language: node_js
node_js:
  - "0.12"
addons:
  code_climate:
    repo_token: 9db7d54a54dec6e32e6ea3aedc47a889c690b8e84a5a85c515f1edea5f906f92
before_script:
  npm i -g jasmine-node
after_script:
  istanbul cover jasmine-node --captureExceptions spec/ && codeclimate < ./coverage/lcov.info
